package com.aqualyzer.ui;

import com.aqualyzer.core.model.Fish;
import com.aqualyzer.ui.components.RangeSlider;

import javax.swing.*;
import java.awt.*;

public class FischEditor extends JDialog {

    private JPanel contentPane;
    private JTextField nameField;
    private JTextField sciNameField;
    private RangeSlider phSlider;
    private RangeSlider tempSlider;
    private JButton abbrechenButton;
    private JButton hinzufuegenButton;
    private JLabel phMinLabel;
    private JLabel tempMinLabel;
    private JLabel phMaxLabel;
    private JLabel tempMaxLabel;
    private JTextArea bemerkungField;
    private RangeSlider o2Slider;
    private RangeSlider salinitySlider;
    private JLabel o2minLabel;
    private JLabel o2maxLabel;
    private JLabel psuMinLabel;
    private JLabel psuMaxLabel;

    public FischEditor(String title) {
        $$$setupUI$$$();
        setTitle(title);
        setContentPane(contentPane);
        setModal(true);
        onTempChanged();
        onPhChanged();
        onO2Changed();
        onSalinityChanged();
        hinzufuegenButton.addActionListener(e -> onOK());
        abbrechenButton.addActionListener(e -> onCancel());
        phSlider.addChangeListener(e -> onPhChanged());
        tempSlider.addChangeListener(e -> onTempChanged());
        o2Slider.addChangeListener(e -> onO2Changed());
        salinitySlider.addChangeListener(e -> onSalinityChanged());
        pack();
        setLocationRelativeTo(null);
    }

    private Fish fish;

    public void setFish(Fish fish) {
        this.fish = fish;
        setupUi();
    }

    public Fish getFish() {
        return fish;
    }

    private void setupUi() {
        if (fish == null) return;

        nameField.setText(fish.getName());
        sciNameField.setText(fish.getScientificName());
        phSlider.setValue(fish.getPhMin().intValue());
        phSlider.setUpperValue(fish.getPhMax().intValue());
        tempSlider.setValue(fish.getTempMin().intValue());
        tempSlider.setUpperValue(fish.getTempMax().intValue());
        o2Slider.setValue(fish.getO2ConcentrationMin().intValue());
        o2Slider.setUpperValue(fish.getO2ConcentrationMax().intValue());
        salinitySlider.setValue(fish.getPsuMin().intValue());
        salinitySlider.setUpperValue(fish.getPsuMax().intValue());
    }

    private void onOK() {
        if (fish == null) {
            fish = new Fish();
        }

        fish.setName(nameField.getText());
        fish.setScientificName(sciNameField.getText());
        fish.setComment(bemerkungField.getText());
        fish.setPsuMin((double) salinitySlider.getValue());
        fish.setPsuMax((double) salinitySlider.getUpperValue());
        fish.setPhMin((double) phSlider.getValue());
        fish.setPhMax((double) phSlider.getUpperValue());
        fish.setTempMin((double) tempSlider.getValue());
        fish.setTempMax((double) tempSlider.getUpperValue());
        fish.setO2ConcentrationMin((double) o2Slider.getValue());
        fish.setO2ConcentrationMax((double) o2Slider.getUpperValue());

        dispose();
    }

    private void onCancel() {
        dispose();
    }

    private void onPhChanged() {
        phMinLabel.setText(String.valueOf(phSlider.getValue()));
        phMaxLabel.setText(String.valueOf(phSlider.getUpperValue()));
    }

    private void onTempChanged() {
        tempMinLabel.setText(String.valueOf(tempSlider.getValue()));
        tempMaxLabel.setText(String.valueOf(tempSlider.getUpperValue()));
    }

    private void onO2Changed() {
        o2minLabel.setText(String.valueOf(o2Slider.getValue()));
        o2maxLabel.setText(String.valueOf(o2Slider.getUpperValue()));
    }

    private void onSalinityChanged() {
        psuMinLabel.setText(String.valueOf(salinitySlider.getValue()));
        psuMaxLabel.setText(String.valueOf(salinitySlider.getUpperValue()));
    }

    private void createUIComponents() {
        phSlider = new RangeSlider();
        tempSlider = new RangeSlider();
        o2Slider = new RangeSlider();
        salinitySlider = new RangeSlider();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        nameField = new JTextField();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(nameField, gbc);
        sciNameField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(sciNameField, gbc);
        phSlider.setMaximum(14);
        phSlider.setUpperValue(14);
        phSlider.setValue(3);
        phSlider.setValueIsAdjusting(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(phSlider, gbc);
        tempSlider.setMinimum(-40);
        tempSlider.setUpperValue(50);
        tempSlider.setValue(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(tempSlider, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Bezeichnung");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label1, gbc);
        final JLabel sciNameLabel = new JLabel();
        sciNameLabel.setText("wissenschaftlicher Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(sciNameLabel, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("pH-Toleranz");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Temperatur-Toleranz (°C)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label3, gbc);
        abbrechenButton = new JButton();
        abbrechenButton.setIcon(new ImageIcon(getClass().getResource("/icons/cancel.png")));
        abbrechenButton.setText("Abbrechen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(abbrechenButton, gbc);
        hinzufuegenButton = new JButton();
        hinzufuegenButton.setIcon(new ImageIcon(getClass().getResource("/icons/accept.png")));
        hinzufuegenButton.setText("Bestätigen");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(hinzufuegenButton, gbc);
        tempMaxLabel = new JLabel();
        tempMaxLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(tempMaxLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        contentPane.add(spacer1, gbc);
        phMaxLabel = new JLabel();
        phMaxLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(phMaxLabel, gbc);
        tempMinLabel = new JLabel();
        tempMinLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(tempMinLabel, gbc);
        phMinLabel = new JLabel();
        phMinLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(phMinLabel, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Sauerstoff-Toleranz (mg/L)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label4, gbc);
        o2Slider.setMaximum(20);
        o2Slider.setUpperValue(20);
        o2Slider.setValue(5);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(o2Slider, gbc);
        o2maxLabel = new JLabel();
        o2maxLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(o2maxLabel, gbc);
        o2minLabel = new JLabel();
        o2minLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(o2minLabel, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Salzgehalt-Toleranz (PSU)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label5, gbc);
        psuMinLabel = new JLabel();
        psuMinLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(psuMinLabel, gbc);
        salinitySlider.setMaximum(80);
        salinitySlider.setUpperValue(50);
        salinitySlider.setValue(30);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(salinitySlider, gbc);
        psuMaxLabel = new JLabel();
        psuMaxLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(psuMaxLabel, gbc);
        bemerkungField = new JTextArea();
        bemerkungField.setLineWrap(true);
        bemerkungField.setRows(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.gridwidth = 3;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 3.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(bemerkungField, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Bemerkung");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label6, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        contentPane.add(spacer2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
