package com.aqualyzer.ui;

import com.aqualyzer.core.model.WaterMeasurement;

import javax.swing.*;
import java.awt.*;
import java.util.Date;

public class MessungEditor extends JDialog {

    private JSpinner dateTimeSpinner;
    private JButton okButton;
    private JButton cancelButton;
    private JTextField stationField;
    private JLabel stationLabel;
    private JSlider phSlider;
    private JSlider temperatureSlider;
    private JSlider o2Slider;
    private JSlider psuSlider;
    private JLabel phValueLabel;
    private JLabel twValueLabel;
    private JLabel o2ValueLabel;
    private JLabel psuValueLabel;
    private JPanel contentPane;


    public MessungEditor() {

        $$$setupUI$$$();
        setTitle("Messung erfassen");
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(okButton);

        dateTimeSpinner.setValue(new Date());

        phSlider.addChangeListener(e -> onPhChanged());
        temperatureSlider.addChangeListener(e -> onTemperatureChanged());
        o2Slider.addChangeListener(e -> onO2Changed());
        psuSlider.addChangeListener(e -> onPsuChanged());

        onPhChanged();
        onTemperatureChanged();
        onO2Changed();
        onPsuChanged();

        okButton.addActionListener(e -> onOK());
        cancelButton.addActionListener(e -> onCancel());

        pack();
        setLocationRelativeTo(null);

    }

    private WaterMeasurement measure;

    public WaterMeasurement getWaterMeasurement() {
        return measure;
    }

    private void onOK() {
        measure = new WaterMeasurement(
                (Date) dateTimeSpinner.getValue(),
                stationField.getText(),
                (double) psuSlider.getValue(),
                (double) phSlider.getValue(),
                (double) temperatureSlider.getValue(),
                (double) o2Slider.getValue()
        );
        dispose();
    }

    private void onCancel() {
        dispose();
    }

    private void onO2Changed() {
        o2ValueLabel.setText(String.valueOf(o2Slider.getValue()));
    }

    private void onPsuChanged() {
        psuValueLabel.setText(String.valueOf(psuSlider.getValue()));
    }

    private void onTemperatureChanged() {
        twValueLabel.setText(String.valueOf(temperatureSlider.getValue()));
    }

    private void onPhChanged() {
        phValueLabel.setText(String.valueOf(phSlider.getValue()));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(dateTimeSpinner, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Zeitstempel");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label1, gbc);
        stationLabel = new JLabel();
        stationLabel.setText("Station");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(stationLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        contentPane.add(spacer1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("pH-Wert");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Wassertemperatur (°C)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Sauerstoffgehalt  (mg/L)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Salzgehalt (PSU)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label5, gbc);
        okButton = new JButton();
        okButton.setIcon(new ImageIcon(getClass().getResource("/icons/accept.png")));
        okButton.setText("Bestätigen");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.weightx = 3.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(okButton, gbc);
        cancelButton = new JButton();
        cancelButton.setIcon(new ImageIcon(getClass().getResource("/icons/cancel.png")));
        cancelButton.setText("Abbrechen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(cancelButton, gbc);
        stationField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(stationField, gbc);
        phSlider = new JSlider();
        phSlider.setMaximum(14);
        phSlider.setValue(7);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(phSlider, gbc);
        temperatureSlider = new JSlider();
        temperatureSlider.setMinimum(-40);
        temperatureSlider.setValue(20);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(temperatureSlider, gbc);
        o2Slider = new JSlider();
        o2Slider.setMaximum(20);
        o2Slider.setValue(10);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(o2Slider, gbc);
        psuSlider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(psuSlider, gbc);
        phValueLabel = new JLabel();
        phValueLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(phValueLabel, gbc);
        twValueLabel = new JLabel();
        twValueLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(twValueLabel, gbc);
        o2ValueLabel = new JLabel();
        o2ValueLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(o2ValueLabel, gbc);
        psuValueLabel = new JLabel();
        psuValueLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(psuValueLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    private void createUIComponents() {

        var dateModel = new SpinnerDateModel();
        dateTimeSpinner = new JSpinner(dateModel);
        dateTimeSpinner.setEditor(new JSpinner.DateEditor(dateTimeSpinner, "dd.MM.yyyy HH:mm"));

    }
}
