package com.aqualyzer.ui;

import javax.swing.*;
import java.awt.*;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;

public class ZeitreihenImporter extends JDialog {

    private String path;
    private Charset charset;
    private char delimiter = ';';
    private JFileChooser filePicker;
    private JPanel contentPane;
    private JTextField delimField;
    private JComboBox charsetDropdown;

    public String getPath() {
        return path;
    }

    public Charset getCharset() {
        return charset;
    }

    public char getDelimiter() {
        return delimiter;
    }

    public ZeitreihenImporter() {
        localizeComponents();
        setTitle(Messages.get("importer.title"));
        setContentPane(contentPane);
        setModal(true);
        pack();
        setLocationRelativeTo(null);


        filePicker.addActionListener(e -> {
            if (e.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
                path = filePicker.getSelectedFile().getAbsolutePath();
                dispose();
            } else if (e.getActionCommand().equals(JFileChooser.CANCEL_SELECTION)) {
                path = null;
                dispose();
            }
        });

        addCharsets();

        charsetDropdown.addActionListener(e -> charset = (Charset) charsetDropdown.getSelectedItem());
        charset = StandardCharsets.ISO_8859_1;

        delimField.addActionListener(e -> {
            var text = delimField.getText();
            if (!text.isEmpty()) delimiter = text.charAt(0);
        });
    }

    private void addCharsets() {
        charsetDropdown.addItem(StandardCharsets.ISO_8859_1);
        charsetDropdown.addItem(StandardCharsets.UTF_8);
        charsetDropdown.addItem(StandardCharsets.US_ASCII);
        charsetDropdown.addItem(StandardCharsets.UTF_16);
        charsetDropdown.addItem(StandardCharsets.UTF_16BE);
        charsetDropdown.addItem(StandardCharsets.UTF_16LE);
        charsetDropdown.setSelectedItem(StandardCharsets.ISO_8859_1);

    }


    private void localizeComponents() {
        filePicker.setApproveButtonText(Messages.get("importer.button.approve"));
        Messages.relabel(contentPane, "Trennzeichen", Messages.get("importer.label.delimiter"));
        Messages.relabel(contentPane, "Kodierung", Messages.get("importer.label.charset"));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        filePicker = new JFileChooser();
        filePicker.setAcceptAllFileFilterUsed(true);
        filePicker.setApproveButtonText("Importieren");
        filePicker.setDragEnabled(true);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(filePicker, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 5.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        contentPane.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Trennzeichen");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label1, gbc);
        delimField = new JTextField();
        delimField.setText(";");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(delimField, gbc);
        charsetDropdown = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(charsetDropdown, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Kodierung");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        contentPane.add(label2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
